# Documentation : https://fly.io/docs/reference/configuration/

app = 'linked-me-api'
primary_region = 'cdg'  # Paris (Charles de Gaulle)

[build]

[env]
  NODE_ENV = 'production'
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'     # Ã‰teint la machine si pas de trafic
  auto_start_machines = true      # Rallume au premier appel
  min_machines_running = 0

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
